package com.myspace.mymortgagedemo;

function double calculateInstallment (double amount, double interest, int tenure){
    
        if (amount == null || interest == null || tenure == 0){
            return 0.0;
        }
        System.out.println("amount = " + amount);
        System.out.println("interest = " + interest);
        System.out.println("tenure = " + tenure);
    	double i = java.lang.Math.pow ( (interest / 100 / 12) + 1, tenure * 12);
		double l = amount * i;
		double m = i - 1;
		double n = interest / 100 / 12; 
		double result = ( l / (m / n));
		System.out.println("i = " + i);
		System.out.println("l = " + l);
		System.out.println("m = " + m);
		System.out.println("n = " + n);
		System.out.println("result = " + result);
		
		return result;
		
}

