package com.myspace.mymortgagedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Property Price")
	private java.lang.Double price;
	@org.kie.api.definition.type.Label("Loan Tenure")
	private java.lang.Integer amortization;
	@org.kie.api.definition.type.Label("Applicant Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Applicant Age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label("Applicant Identification ID")
	private java.lang.String iid;

	@org.kie.api.definition.type.Label("Applicant Income")
	private java.lang.Double income;

	@org.kie.api.definition.type.Label("Margin of Finance")
	private java.lang.Double margin;

	@org.kie.api.definition.type.Label("Credit Rating")
	private java.lang.Integer creditRating;

	@org.kie.api.definition.type.Label(value = "Error Message")
	private java.lang.String message;

	public Application() {
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.Integer getAmortization() {
		return this.amortization;
	}

	public void setAmortization(java.lang.Integer amortization) {
		this.amortization = amortization;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getIid() {
		return this.iid;
	}

	public void setIid(java.lang.String iid) {
		this.iid = iid;
	}

	public java.lang.Double getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Double income) {
		this.income = income;
	}

	public java.lang.Double getMargin() {
		return this.margin;
	}

	public void setMargin(java.lang.Double margin) {
		this.margin = margin;
	}

	public java.lang.Integer getCreditRating() {
		return this.creditRating;
	}

	public void setCreditRating(java.lang.Integer creditRating) {
		this.creditRating = creditRating;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public Application(java.lang.Double price, java.lang.Integer amortization,
			java.lang.String name, java.lang.Integer age, java.lang.String iid,
			java.lang.Double income, java.lang.Double margin,
			java.lang.Integer creditRating, java.lang.String message) {
		this.price = price;
		this.amortization = amortization;
		this.name = name;
		this.age = age;
		this.iid = iid;
		this.income = income;
		this.margin = margin;
		this.creditRating = creditRating;
		this.message = message;
	}

}