package com.myspace.mymortgagedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Property Price")
	private java.lang.Double price;
	@org.kie.api.definition.type.Label("Down Payment")
	private java.lang.Double downPayment;
	@org.kie.api.definition.type.Label("Loan Tenure")
	private java.lang.Integer amortization;
	@org.kie.api.definition.type.Label("Interest Rate")
	private java.lang.Double interest;

	@org.kie.api.definition.type.Label("Applicant Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Applicant Age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label("Applicant Identification ID")
	private java.lang.String iid;

	@org.kie.api.definition.type.Label("Credit Rating")
	private java.lang.String creditRating;

	@org.kie.api.definition.type.Label("Applicant Income")
	private java.lang.Double income;

	@org.kie.api.definition.type.Label("Application Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("Message")
	private java.lang.String message;

	@org.kie.api.definition.type.Label("Margin of Finance")
	private java.lang.Double margin;

	@org.kie.api.definition.type.Label("Monthly Installment")
	private java.lang.Double installment;

	@org.kie.api.definition.type.Label(value = "Mortgage Amount")
	private java.lang.Double mortgageAmount;

	public Application() {
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.Double getDownPayment() {
		return this.downPayment;
	}

	public void setDownPayment(java.lang.Double downPayment) {
		this.downPayment = downPayment;
	}

	public java.lang.Integer getAmortization() {
		return this.amortization;
	}

	public void setAmortization(java.lang.Integer amortization) {
		this.amortization = amortization;
	}

	public java.lang.Double getInterest() {
		return this.interest;
	}

	public void setInterest(java.lang.Double interest) {
		this.interest = interest;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getIid() {
		return this.iid;
	}

	public void setIid(java.lang.String iid) {
		this.iid = iid;
	}

	public java.lang.String getCreditRating() {
		return this.creditRating;
	}

	public void setCreditRating(java.lang.String creditRating) {
		this.creditRating = creditRating;
	}

	public java.lang.Double getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Double income) {
		this.income = income;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.Double getMargin() {
		return this.margin;
	}

	public void setMargin(java.lang.Double margin) {
		this.margin = margin;
	}

	public java.lang.Double getInstallment() {
		return this.installment;
	}

	public void setInstallment(java.lang.Double installment) {
		this.installment = installment;
	}

	public java.lang.Double getMortgageAmount() {
		return this.mortgageAmount;
	}

	public void setMortgageAmount(java.lang.Double mortgageAmount) {
		this.mortgageAmount = mortgageAmount;
	}

	public Application(java.lang.Double price, java.lang.Double downPayment,
			java.lang.Integer amortization, java.lang.Double interest,
			java.lang.String name, java.lang.Integer age, java.lang.String iid,
			java.lang.String creditRating, java.lang.Double income,
			java.lang.String status, java.lang.String message,
			java.lang.Double margin, java.lang.Double installment,
			java.lang.Double mortgageAmount) {
		this.price = price;
		this.downPayment = downPayment;
		this.amortization = amortization;
		this.interest = interest;
		this.name = name;
		this.age = age;
		this.iid = iid;
		this.creditRating = creditRating;
		this.income = income;
		this.status = status;
		this.message = message;
		this.margin = margin;
		this.installment = installment;
		this.mortgageAmount = mortgageAmount;
	}

}