package com.myspace.mymortgagedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approval implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Approval() {
    }




}