package com.myspace.mymortgagedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorMessage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ErrorMessage() {
    }




}